#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dri2proto
Version  : 2.8
Release  : 3
URL      : http://xorg.freedesktop.org/releases/individual/proto/dri2proto-2.8.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/dri2proto-2.8.tar.bz2
Summary  : DRI2 extension headers
Group    : Development/Tools
License  : ICU
Requires: dri2proto-doc

%description
Direct Rendering Infrastructure 2 Extension
This extension defines a protocol to securely allow user applications to access
the video hardware without requiring data to be passed through the X server.

%package dev
Summary: dev components for the dri2proto package.
Group: Development

%description dev
dev components for the dri2proto package.


%package doc
Summary: doc components for the dri2proto package.
Group: Documentation

%description doc
doc components for the dri2proto package.


%prep
%setup -q -n dri2proto-2.8

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/dri2proto.h
/usr/include/X11/extensions/dri2tokens.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/dri2proto/*
